image: node:latest
stages:
    - install
    - build
    - test
install:
    stage: install
    cache:
        key:
            files:
                - yarn.lock
        paths:
            - node_modules
    before_script:
        - yarn config set cache-folder node_modules
    script:
        - yarn install

build:
    stage: build
    script:
        - yarn build

test:
    stage: test
    script:
        - yarn test
