deploy:
    image: docker
    services:
        - docker:dind
    script:
        - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN
        - docker build -t $CI_REGISTRY_IMAGE . --build-arg TURBO_TEAM=$TURBO_TEAM --build-arg TURBO_TOKEN=$TURBO_TOKEN
        - docker push $CI_REGISTRY_IMAGE
