image: node:latest

stages:
    - install
    - build
    - test

Install:
    stage: install
    cache:
        key:
            files:
                - yarn.lock
        paths:
            - node_modules
    script:
        - yarn install --cache-folder node_modules

Test:
    stage: test
    cache:
        key:
            files:
                - yarn.lock
        paths:
            - node_modules
        policy: pull
    script:
        - yarn test

Build:
    stage: build
    cache:
        key:
            files:
                - yarn.lock
        paths:
            - node_modules
        policy: pull
    script:
        - yarn build
