version: '3.8'

services:
    server:
        build:
            dockerfile: ./apps/server/Dockerfile
            context: .
            args:
                - TURBO_TEAM=${TURBO_TEAM}
                - TURBO_TOKEN=${TURBO_TOKEN}
        restart: always
        env_file:
            - ./.env
        ports:
            - 3001:3001
        networks:
            - app_network
    client:
        build:
            dockerfile: ./apps/client/Dockerfile
            context: .
            args:
                - TURBO_TEAM=${TURBO_TEAM}
                - TURBO_TOKEN=${TURBO_TOKEN}
        restart: always
        env_file:
            - ./.env
        ports:
            - 3000:3000
        networks:
            - app_network

networks:
    app_network:
        external: true
