version: '3.8'

services:
    server:
        build:
            dockerfile: ./apps/server/Dockerfile
            context: .
            args:
                - TURBO_TEAM=${TURBO_TEAM}
                - TURBO_TOKEN=${TURBO_TOKEN}
        restart: always
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
    client:
        build:
            dockerfile: ./apps/client/Dockerfile
            context: .
            args:
                - TURBO_TEAM=${TURBO_TEAM}
                - TURBO_TOKEN=${TURBO_TOKEN}
        restart: always
        ports:
            - ${CLIENT_PORT}:${CLIENT_PORT}
